### ISSUE TITLE
Installing hugo appears to hang

### ISSUE THREAD

**Issue by importhuman** [buildpack/docs#395]
Always get stuck at the first step:

```
➜  docs git:(previous-image-docs) ✗ make serve
> Installing hugo...
cd tools; go install -mod=mod --tags extended github.com/gohugoio/hugo
```

Additional information:
OS: macOS (Big Sur 11.4)
jq version 1.6
xcode-select version 2384
Hugo installed on device via homebrew

**Comment by dfreilich** [comment]
I'm for trying 3

**Comment by dfreilich** [comment]
I've also experience some long build times. I'm for pulling it from the release, or, at a minimum, printing out that 
```
This may take a while, depending on your connection
```

**Comment by jromero** [comment]
I agree with either of the proposed solutions.

1. Print a statement that reads: "This may take a while, depending on your connection."
2. Download `hugo` from [releases](https://github.com/gohugoio/hugo/releases) based on OS/arch to a local directory and use that.

**Comment by Harshita-Kanal** [comment]
Can I take this up, which approach should I go with?

**Comment by samj1912** [comment]
@Harshita-Kanal it would be nicer to have the latter :)

**Comment by Harshita-Kanal** [comment]
> I agree with either of the proposed solutions.
> 
> 1. Print a statement that reads: "This may take a while, depending on your connection."
> 2. Download `hugo` from [releases](https://github.com/gohugoio/hugo/releases) based on OS/arch to a local directory and use that.

Here, the local directory could be `/usr/local/bin` in case of linux based systems? or install it in a temporary directory say ` /tmp/`

**Comment by samj1912** [comment]
> > I agree with either of the proposed solutions.
> > 
> > 1. Print a statement that reads: "This may take a while, depending on your connection."
> > 2. Download `hugo` from [releases](https://github.com/gohugoio/hugo/releases) based on OS/arch to a local directory and use that.
> 
> Here, the local directory could be `/usr/local/bin` in case of linux based systems? or install it in a temporary directory say ` /tmp/`

Probably easiest to put it in the project directory under tools/bin and add it to gitignore.
