### ISSUE TITLE
Update creating a buildpack tutorial

### ISSUE THREAD

**Issue by jromero** [buildpack/docs#51]
edge docs still mention old plan.toml system (pass via STDIN into bin/build); the schema of bin/detect's plan.toml would not support this example; and `bin/build` consumes the plan.toml via `$3` now.
    https://github.com/buildpack/docs/blob/edge/content/docs/create-buildpack/caching.md

_Originally posted by @drnic in https://github.com/buildpack/docs/issues/47#issuecomment-526805295_

**Comment by ameyer-pivotal** [comment]
Just a quick reminder to PR to the `edge` branch when this goes up
